### ISSUE TITLE
Fps drops when overlay is shown

### ISSUE THREAD

**Issue by Jujumatic** [inorton/EDMCOverlay#22]
Hi there, I am using Windowed Borderless with 60hz and VSync.
Whenever the overlay pops up, fps cuts in half and as soon as it goes away, back to a stable 60 fps. Plis fix :)

**Comment by inorton** [comment]
Hmm I will take a look

**Comment by inorton** [comment]
Hi, How many CPUs does your machine have?

**Comment by pgschk** [comment]
I also have pretty bad FPS loss and some screen tearing and stuttering when the overlay is displayed. Worst when docking, dropping from ~110-120 to around 80 fps, however it feels worse than that.

I'm in borderless with Vsync off and a Gsync display and card (GeForce GTX 1660 Super).

Since you where asking for CPUs, I have an Intel Core i7-6700, so once CPU, four cores

I'd love to help improve this, since I really like the functionality but it feels almost unplayable to me :(

**Comment by inorton** [comment]
Thanks, It's been very difficult to get consistent results. I'm not calling into DirectX I'm using the .Net drawing APIs on a transparent window and it seems different cards yield very different results.

I had a couple of problems myself after updating my nvidia drivers, then the problem went away without any code changes.

**Comment by pgschk** [comment]
Yeah, I agree it's pretty inconsistent, even on the same hardware without driver changes, sometimes it's barely noticeable. Just let me know should you ever have a hunch and I can help in any way.

**Comment by inorton** [comment]
Can't really do a huge amount about this, and it is different depending on the GPU/CPU combo
